### ISSUE TITLE
Ошибка сборки и запуска проекта

### ISSUE THREAD

**Issue by bankoViktor** [lord-vesel/dcs-doc#73]
Здравствуйте,

команда `pip3 install -r requirements.txt` выдает: 
`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

команда `mkdocs serve` выдает: 
`Error: Config file 'mkdocs.yml' does not exist.`

При смене текущей директории (например `cd en`), все равно `mkdocs serve` оканчивается неудачей.

Выхлоп:
```
Winston@DESKTOP-PC MINGW64 /d/source/repos/dcs-doc/en (av-8bna)
$ mkdocs serve 
INFO     -  Building documentation...
WARNING  -  Config value: 'plugins'. Warning: ('full_path_in_title', 'Unrecognised configuration name: full_path_in_title')
INFO     -  Cleaning site directory
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python310\lib\site-packages\mkdocs\__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "C:\Python310\lib\site-packages\mkdocs\commands\serve.py", line 63, in serve
    config = builder()
  File "C:\Python310\lib\site-packages\mkdocs\commands\serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "C:\Python310\lib\site-packages\mkdocs\commands\build.py", line 282, in build
    files = config['plugins'].run_event('files', files, config=config)
  File "C:\Python310\lib\site-packages\mkdocs\plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "C:\Python310\lib\site-packages\tags\plugin.py", line 60, in on_files
    self.metadata.append(get_metadata(f.src_path, config["docs_dir"]))
  File "C:\Python310\lib\site-packages\tags\plugin.py", line 128, in get_metadata
    metadata = extract_yaml(f)
  File "C:\Python310\lib\site-packages\tags\plugin.py", line 116, in extract_yaml
    for line in f:
  File "C:\Python310\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1540: character maps to <undefined>
```

**Comment by lord-vesel** [comment]
Привет, да, pip3 нужно выполнять в том же каталоге, в котором лежит readme, где эта инструкция написана.

UnicodeDecodeError вероятно вызвана либо неправильной кодировкой редактируемых *.md, либо терминалом, не поддерживающим UTF-8 (скорее всего). Рекомендую попробовать в Windows Terminal и WSL2, с ними никаких проблем нет.

**Comment by bankoViktor** [comment]
Ошибку вызывает плагин `tags` в файле `en/mkdocs.yml` в файле, убрал его и сервер стартовал

```
plugins:
    - search:
        lang: ['en', 'ru']
        full_path_in_title: yes
    - tags              <----- вот этот плагин
```

**Comment by lord-vesel** [comment]
Странно, у меня не воспроизводится ни на одной версии питона под линуксом и WSL. Плагин пока что не используется, так что ничего страшного.
